FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG AJO_ALLOWED_DEV_ORIGINS
ENV AJO_ALLOWED_DEV_ORIGINS=$AJO_ALLOWED_DEV_ORIGINS
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_REFRESH_INTERVAL_SECONDS
ARG NEXT_PUBLIC_DEFAULT_PAGE_SIZE
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL NEXT_PUBLIC_REFRESH_INTERVAL_SECONDS=$NEXT_PUBLIC_REFRESH_INTERVAL_SECONDS NEXT_PUBLIC_DEFAULT_PAGE_SIZE=$NEXT_PUBLIC_DEFAULT_PAGE_SIZE
RUN npm run build
FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app .
USER node
CMD ["npm", "run", "start"]
