"""initial_platform"""
from alembic import op
import sqlalchemy as sa

revision = 'e3c411b370b1'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_status', sa.String(), nullable=False),
    sa.Column('pseudonym', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_counter', sa.BigInteger(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('pseudonym')
    )
    op.create_table('platform_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_audit_resource'), 'platform_audit', ['resource'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limits',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('until', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bank_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('masked', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mandate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('circles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('seed', sa.Text(), nullable=False),
    sa.Column('commitment', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circles_state'), 'circles', ['state'], unique=False)
    op.create_table('data_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('id_fingerprint', sa.String(), nullable=False),
    sa.Column('biometric_fingerprint', sa.String(), nullable=True),
    sa.Column('device_fingerprint', sa.String(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_cases_biometric_fingerprint'), 'identity_cases', ['biometric_fingerprint'], unique=False)
    op.create_index(op.f('ix_identity_cases_device_fingerprint'), 'identity_cases', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_identity_cases_id_fingerprint'), 'identity_cases', ['id_fingerprint'], unique=False)
    op.create_index(op.f('ix_identity_cases_user_id'), 'identity_cases', ['user_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('secure_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('refresh_hash', sa.String(), nullable=False),
    sa.Column('expires', sa.BigInteger(), nullable=False),
    sa.Column('refresh_expires', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('token_hash'),
    sa.UniqueConstraint('refresh_hash')
    )
    op.create_index(op.f('ix_session_tokens_user_id'), 'session_tokens', ['user_id'], unique=False)
    op.create_table('verification_challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires', sa.BigInteger(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circle_contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('circle_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('pdf', sa.LargeBinary(), nullable=False),
    sa.Column('pdf_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circle_id', 'version')
    )
    op.create_table('complaints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('circle_id', sa.String(), nullable=False),
    sa.Column('filer_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assignee'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['filer_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('circle_id', sa.String(), nullable=False),
    sa.Column('generator_id', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('recipient_hash', sa.String(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('expires', sa.BigInteger(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['generator_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_table('participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('circle_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('inviter_id', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('joined_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circle_id', 'user_id')
    )
    op.create_index(op.f('ix_participants_circle_id'), 'participants', ['circle_id'], unique=False)
    op.create_index(op.f('ix_participants_user_id'), 'participants', ['user_id'], unique=False)
    op.create_table('scheduled_payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('circle_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('business_key', sa.String(), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt', sa.String(), nullable=True),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.CheckConstraint('amount_minor >= 0'),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circle_id', 'business_key')
    )
    op.create_index(op.f('ix_scheduled_payments_circle_id'), 'scheduled_payments', ['circle_id'], unique=False)
    op.create_index(op.f('ix_scheduled_payments_date'), 'scheduled_payments', ['date'], unique=False)
    op.create_table('trust_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('circle_id', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('contract_signatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('typed_name', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('signed_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['circle_contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'user_id')
    )
    op.create_table('ledger_postings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('circle_id', sa.String(), nullable=False),
    sa.Column('due_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_key', sa.String(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['due_id'], ['scheduled_payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', 'account')
    )
    op.create_index(op.f('ix_ledger_postings_circle_id'), 'ledger_postings', ['circle_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('due_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['due_id'], ['scheduled_payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###
    from app.platform.integrity import install_guards
    install_guards(op.get_bind())

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_ledger_postings_circle_id'), table_name='ledger_postings')
    op.drop_table('ledger_postings')
    op.drop_table('contract_signatures')
    op.drop_table('trust_events')
    op.drop_index(op.f('ix_scheduled_payments_date'), table_name='scheduled_payments')
    op.drop_index(op.f('ix_scheduled_payments_circle_id'), table_name='scheduled_payments')
    op.drop_table('scheduled_payments')
    op.drop_index(op.f('ix_participants_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_circle_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_table('invitations')
    op.drop_table('complaints')
    op.drop_table('circle_contracts')
    op.drop_table('verification_challenges')
    op.drop_index(op.f('ix_session_tokens_user_id'), table_name='session_tokens')
    op.drop_table('session_tokens')
    op.drop_table('secure_documents')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_identity_cases_user_id'), table_name='identity_cases')
    op.drop_index(op.f('ix_identity_cases_id_fingerprint'), table_name='identity_cases')
    op.drop_index(op.f('ix_identity_cases_device_fingerprint'), table_name='identity_cases')
    op.drop_index(op.f('ix_identity_cases_biometric_fingerprint'), table_name='identity_cases')
    op.drop_table('identity_cases')
    op.drop_table('data_requests')
    op.drop_index(op.f('ix_circles_state'), table_name='circles')
    op.drop_table('circles')
    op.drop_table('bank_links')
    op.drop_table('rate_limits')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_platform_audit_resource'), table_name='platform_audit')
    op.drop_table('platform_audit')
    op.drop_table('accounts')
    # ### end Alembic commands ###
