"""Initial editorial content based on the supplied landing-page screens."""
DEFAULT_CONTENT = {
 'meta': {'title':'Ajo — Your people. Your circle. Your next step.','description':'Rotating savings circles with clear agreements, shared schedules and a record of every commitment.'},
 'nav': {'how':'How it works','safeguards':'Safeguards','circles':'Find a circle','signin':'Sign in'},
 'hero': {'lines':['Your people.','Your circle.','Your next step.'],'body':'Ajo is a rotating savings circle. A group agrees on an amount and a schedule, everyone contributes each round, and each round one member receives the whole pot — until everyone has had their turn.','primary':'Find a circle','secondary':'See how it works','notice':'Sandbox preview — no real money moves yet.'},
 'calculator': {'title':'See your plan take shape','subtitle':'Move the sliders to shape a circle','contribution':'Contribution each round','members':'People in the circle','turn':'Your payout turn','pot':'you receive the pot','total':'Total you contribute','frequency':'Contribution frequency','currency':'Currency','note':'Illustration uses matching contribution and collection frequencies, excludes fees and missed payments, and is not an investment return. Keep contributing after your payout until the cycle ends.'},
 'how': {'title':'A shared agreement. A turn for everyone.','body':'Rotating savings circles have been run between friends, families and neighbours for generations — under names like ajo, esusu, tanda, hui and chit. Ajo keeps the same agreement and does the record-keeping for you.','steps':[{'title':'Gather your circle','body':'Bring together people you trust, or join an open circle from the marketplace with a shared goal.'},{'title':'Agree before starting','body':'Set the amount, the frequency and the payout order up front. Everyone reviews and accepts the agreement and full schedule before the cycle begins.'},{'title':'Follow the whole cycle','body':'Contribute each round, take your turn receiving the pot, and see every commitment recorded along the way.'}]},
 'safeguards': {'title':'Clear terms, kept in writing.','body':"The hardest part of an informal savings circle is never the maths — it’s knowing where everyone stands. Ajo makes the agreement explicit and keeps a running record that every member can see.",'items':[{'title':'Everyone sees the same schedule','body':"Amount, frequency, payout order and every member’s turn are fixed when the circle starts."},{'title':'Reminders before each round','body':'Review upcoming contribution dates and notifications in the app. External email, SMS and push delivery are simulated in this sandbox.'},{'title':'A record you can point to','body':'Contributions, payouts and missed rounds are logged, so the group can review who paid what.'},{'title':'Not an investment','body':"A circle doesn’t earn returns. You get back what the group puts in — the benefit is timing, not growth."}]},
 'circles': {'title':'Circles open right now','body':'Browse open circles from the Ajo community, or start one with people you already know.','cta':'Browse the marketplace','examples':'Illustrative circles · UI mockup (examples only)','empty':'No public circles are recruiting yet. You can start a circle of your own.'},
 'faq': {'title':'Before you join','items':[{'question':'Is this an investment?','answer':"No. A circle pools contributions and hands the pot to one member each round — there’s no interest, return or growth. What changes is when you get access to a lump sum, not how much."},{'question':'What happens if someone misses a contribution?','answer':'A missing contribution can delay a payout. Payment status is recorded, and members can raise a report. Review the agreed rules before joining; a fully funded pot is not guaranteed.'},{'question':'How is the payout order decided?','answer':'The circle can agree a manual order or use a committed random draw. Everyone reviews the resulting order and accepts the agreement before the cycle begins.'},{'question':'Can I use real money? What are the fees?','answer':'This is a sandbox with simulated payments. Live providers, supported markets and final fees are not yet configured. Applicable fees must be disclosed in the agreement before members accept.'}]},
 'closing': {'title':'Start with the people you trust.','body':'Shape a plan in the sandbox, or browse circles other members have opened. Nothing moves until everyone agrees.','primary':'Create a circle','secondary':'Browse open circles'},
 'footer': {'tagline':'Contributions and commitments, clearly recorded.','how':'How it works','circles':'Circles','terms':'Terms','privacy':'Privacy'},
 'legal': {'terms_title':'Sandbox terms — draft','terms_body':'This preview uses simulated payments and is intended for exploring the product. Final service terms, supported markets and provider arrangements remain to be established before launch. The circle agreement records each member’s accepted obligations.','privacy_title':'Privacy information — sandbox preview','privacy_body':'The local sandbox stores account details, circle records and submitted identity information. Identity evidence is encrypted and available to authorized reviewers. Members can use the account area to request a data export or deletion review. A final public privacy policy will be provided before launch.'}
}
